### ISSUE TITLE
[Question]Do we still need this package in our current times?

### ISSUE THREAD

**Issue by acory** [Collaborne/lit-flexbox-literals#1]
All major browsers support Flex Layout now, so vendor prefixes are no longer needed.
Unless you need to support IE you shouldn't need this package right?

**Comment by ankon** [comment]
> Unless you need to support IE you shouldn't need this package right?

Well, there might be still reasons for doing just that, so purely from there: Yes, likely one still could need this.

But: We're no longer using Webcomponents/Polymer/LitElement, and from that perspective this repository still exists to support some legacy applications that used this. You probably should not use this unless you know that you need it.
